<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

| Term       | Brief description |
|------------|:-----------------|
| Subsetting | Select a single element, group of elements or smaller dataset from a data structure |
| Indexing   | Select one element from a data structure |
| Slicing    | Select a range of elements from a data structure |
| Masking    | Select elemnts(s) based on a condition from a data structure|

# Exercise 2

In [14]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

column_1 = np_array_2d[:, 0]
column_1_int = column_1.astype(int)

np_mask = column_1_int % 2 == 1
column_2_odd = np_array_2d[np_mask, 1]

print(column_2_odd)


['A' 'C' 'E' 'G' 'I']


# Exercise 3

In [15]:
import numpy as np

np_array = np.array(
[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

np_vectorised_array = np.sign(np_array - 50).astype(int)

print(np_vectorised_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
