<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [ ]:
#python lists

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0])
print(py_super_names[0])
print(py_super_names[2])    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.
py_super_names[-1]   # Reverse indexing

Natasha Romanoff
Black Widow
Doctor Strange


'Doctor Strange'

In [ ]:
#numpy arrays
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

#dictionary
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

superhero_info["Natasha Romanoff"]  #Black window
superhero_info.keys()   #dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])
superhero_info.values() #dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [ ]:
#2D list or array
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

Lists are general-purpose, while NumPy arrays are specialized for efficient scientific and mathematical computing. 

Python list is heterogeneous data type and numpy array must be homogeneous

## 2.1 Size

In [ ]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

len(py_list_2d)
len(np_array_2d)
np_array_2d.shape # shape is a property/attribute of the NumPy array

(10, 2)

## 2.2 Arrays are fussy about type

In [8]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [11]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
np_array + 10
#py_list + 10        # Won't work!

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [ ]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2 # Lists [1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
np_array_1 + np_array_2 # Arrays array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list*2 # List [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
np_array*2 # Arrays array([ 2,  4,  6,  8, 10])

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array**2 #array([ 1,  4,  9, 16, 25])

#py_list**2                      # Won't work!  

[2, 4]

## 2.7 Asking questions

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)  

py_list == 3     # Works, but what IS the question? -> 
                 # “Is the entire list [1, 2, 3, 4, 5] equal to the integer 3?”
                 # That question is always False, because: 
                 # a list is never equal to an integer

np_array == 3 # array([False, False,  True, False, False])
np_array > 3  # array([False, False, False,  True,  True])

False

## 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
#py_list.sum()   # Won't work!
np_array.sum()  # np.int64(15)
np_array.max()  #np.int64(5)
np_array.min()  #np.int64(1)
np_array.mean() #np.float64(3.0)
np_array.std()  #np.float64(1.4142135623730951)

## Footnotes

an operation on a list works on the whole list. In contrast, an operation on an array works on the individual elements of the array.

In [ ]:
## elements from 1 to 4 in increments of 2 (increment is subsetting)  
py_list[1:5:2]

In [7]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
mask = np_array > 2
mask

array([False, False,  True,  True,  True])